### ISSUE TITLE
Cloudflare & CSP issue: JS - Cross to clear input field does not work on result page

### ISSUE THREAD

**Issue by pro-sumer** [searxng/searxng-docker#259] opened 2024-08-10 17:55 UTC
EDIT: TL;DR; .. the user reports a CSP issue cause by combination oft the CSP header from the Caaddy in the docker image and a Cloudflare proxy ..

---

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
 2024.8.9+f1c05e7c1

**How did you install SearXNG?**
searxng-docker

**What happened?**
Cross to clear input field does not work on result page (does work on start page) 

**How To Reproduce**
1. Search for any text
2. Click on the cross in the input field on the results page

**Expected behavior**
Input field is cleared after clicking on cross

**Screenshots & Logs**
![Input@2x](https://github.com/user-attachments/assets/5f75db2c-a671-4e53-aeef-3241ff614ec6)

**Additional context**
Seems to work fine on public instances?

**Comment by pro-sumer** [comment] 2024-08-11 13:38
Note: when changing
```
script-src 'self'
```
into
```
script-src 'self' 'unsafe-inline
```
in the Caddyfile the errors are gone, but the cross still does not work.

**Comment by return42** [comment] 2024-08-11 13:40
> in `Caddyfile` the errors are gone, but the cross still does not work.

Check again in browser's developer tools .. there might be other reasons why the JavaScript Code of the button is not loaded or executed.

**Comment by pro-sumer** [comment] 2024-08-11 13:50
I tried again after removing all the `Content-Security-Policy` entries.

Not a single error/warning, but still nothing happens when I click on the cross (it does turn blue when I hove the cursor over it).

**Comment by return42** [comment] 2024-08-11 14:14
Just to check other JS implementation do work: when you type `h` (cursor should not in the search box) do you see a help about the hotkeys pop up:

![image](https://github.com/user-attachments/assets/0ccba1a9-33a8-4697-9b40-4d2e713ff4a9)

**Comment by pro-sumer** [comment] 2024-08-11 14:38
No, `h` does nothing at all.

For a moment I thought it fixed it by adding `cdnjs.cloudflare.com` to `script-src` (since I use Cloudflare's proxy), because when I did that, the cross did work in Safari on Mac. However, it did still not work in Mobile Safari on iPhone/iPad. When I then returned to my Mac it did not work there anymore either... (without me changing anything)

**Comment by return42** [comment] 2024-08-11 15:00
> since I use Cloudflare's proxy)

oh no, not really? .. we are fighting with cloudflare quirks? .. Sorry I'm out.

Please understand, we do not support Cloudflare setups: it's not recommended to use Cloudflare as reverse proxy because it MITM every request, which is a disaster for user's privacy.

BTW Cloudflare is more or less the cause of such a lot of issues: https://github.com/search?q=org%3Asearxng+cloudflare&type=issues

@pro-sumer it is not against you, but it is simply wrong in the matter and we do not want to support such wrong ways, please understand that I have to close this thread now.

**Closed by return42** 2024-08-11 15:00 UTC
Labels: bug
